classDiagram
    namespace Person_Commands {
        class CreatePerson
        class RenamePerson
        class DeletePerson
        class AddPaymentOption
        class DeletePaymentOption
    }
    
    namespace Group_Commands {
        class CreateGroup
        class RenameGroup
        class DeleteGroup
        class InviteToGroup
        class AcceptGroupInvite
        class RejectGroupInvite
    }

    namespace Request_Commands {
        class CreateMoneyRequest
        class AcceptMoneyRequest
        class RejectMoneyRequest
    }